version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgresNode
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
     
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  mysql:
    image: mysql:5.7
    container_name: mysqlNode
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
      - "3309:3306"
    
    volumes:
      - mysql-db-volume:/var/lib/mysql

  airflow:
    image: apache/airflow:2.10.5
    depends_on:
      - postgres
      - mysql
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_ALT=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW__WEBSERVER__AUTHENTICATE=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: ["webserver"]

  scheduler:
    image: apache/airflow:2.10.5
    depends_on:
      - postgres
      - mysql  
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_ALT=mysql+mysqlconnector://airflow:airflow@mysql:3306/airflow
      - AIRFLOW__WEBSERVER__AUTHENTICATE=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
    command: ["scheduler"]

volumes:
  postgres-db-volume:
  mysql-db-volume:
